default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  primary:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

